export default {
    products: [{
            _id: '1',
            name: 'Brand-X road',
            category: 'Bike',
            image: '/images/product1.jpg',
            price: 159,
            brand: 'Brand-X',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: '26 Inch Leopard Bike',
            category: 'Bike',
            image: '/images/product2.jpg',
            price: 70,
            brand: 'Smyths Toys',
            rating: 5,
            numReviews: 51,
        },
        {
            _id: '3',
            name: 'Running LeopardApplicable',
            category: 'bike',
            image: '/images/product3.jpg',
            price: 259,
            brand: 'Leopard',
            rating: 4,
            numReviews: 45,
        },
        {
            _id: '4',
            name: 'Honda CB Unicorn Bike',
            category: 'Moto',
            image: '/images/product4.jpg',
            price: 1190,
            brand: 'Honda',
            rating: 3.5,
            numReviews: 198,
            countInStock: 6,
        },
        {
            _id: '5',
            name: 'Kid Bike BMX',
            category: 'bike',
            image: '/images/product5.jpg',
            price: 19,
            brand: 'BMX',
            rating: 3.5,
            numReviews: 89,
            countInStock: 6,
        },
        {
            _id: '6',
            name: ' Harley-DavidsonLiveWire ',
            category: 'Moto',
            image: '/images/product6.jpg',
            price: 1285,
            brand: 'Harley-Davidson',
            rating: 4.5,
            numReviews: 45,
            countInStock: 6,
        },
    ],
};